import { NameValue } from '../models/name-value';
import { HttpMethod } from 'blocking-proxy/built/lib/webdriver_commands';

/**
 * represent an http request.
 */
export class RequestProvider {
    
    //the route of the url  
    private route: string[];
  
    //the params to include in the url
    private params: NameValue[];
  
    //the request body
    private _body: any = null;
  
    //the constructed url
    private _url: string = null;
  
    //the request type
    private _requestType: HttpMethod;
  
    /**
     * get the request type asociated with this provider.
     */
    get requestType(): string {
      return this._requestType;
    }
  
    /**
     * get the request body or null if is not available.
     */
    get body(): any {
      return this._body;
    }
  
    /**
    * get the url generated by this provider
    */
    get url(): string {
  
      if (!this._url) {
        //create the url
        let url = this.route.join('/');
        let parsedParams: string[] = [];
  
        this.params.forEach((v) => {
          parsedParams.push([v.name, v.value].join('='));
        });
  
        this._url = encodeURI(url + '?' + parsedParams.join('&'));
      }
      
      return this._url;
  
    }
  
    constructor(route: string[], params: NameValue[], requestType: HttpMethods, body: any) {
  
      //clone arrays
      this.route = route.slice(0);
      this.params = params.slice(0);
      
      this._requestType = requestType;
      this._body = body;
    }
  
    //Start of the fluent api
    //-------------------------------------------------------------------------------------------------------
  
    /**
     * add a path param to the url.
     * @param param the param to add to the url.
     */
    at(param: string): RequestProvider {
      return new RequestProvider(this.route.concat(param), this.params, this._requestType, this._body);
    }
  
    /**
     * Add a query param to the url (only valid for GET and DELETE requests)
     * @param name the name of the parameter.
     * @param value the value of the parameter.
     */
    withParam(name: string, value: string): RequestProvider {
      if (this._requestType != 'GET' && this._requestType != 'DELETE' )
        throw "query params are only valid for GET and DELETE requests.";
  
      return new RequestProvider(this.route, this.params.concat(new NameValue(name, value)), this._requestType, this._body);
    }
  
    /**
     * add body to the request (only valid for POST and PUT requests)
     * @param body the body to add
     */
    withBody(body: any): RequestProvider {
      if (this._requestType != 'POST' && this._requestType != 'PUT')
        throw "request body is only valid for POST and PUT requests.";
  
      if (this._body != null)
        throw "request body can only be assigned one time.";
  
      return new RequestProvider(this.route, this.params, this._requestType, body);
    }
  
  }
  